### ISSUE TITLE
how would it be on the contrary to export the plc array to a json file?

### ISSUE THREAD

**Issue by runtimevic** [benhar-dev/tchmi-load-structure-from-json#1]
Hello Ben,
how would it be on the contrary to export the plc array to a json file?
I would very much like to know the function to be able to export the plc array and get the json file in a local location of the pc...
I found this:
https://wicg.github.io/file-system-access/
https://googlechromelabs.github.io/text-editor/
https://github.com/GoogleChromeLabs/text-editor
https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API
https://developer.mozilla.org/en-US/docs/Web/API/FileSystemWritableFileStream
https://fjolt.com/article/javascript-new-file-system-api
https://blog.excalidraw.com/browser-fs-access/
but I don't know very well how to implement it in javascript with the TE2000,
Best regards, Víctor.

**Comment by benhar-dev** [comment]
Hi Victor, yes the export plc array / structure to json is possible and I currently do this on another project.  The only limitation with the implementation is that it downloads straight to the users download directory, rather than showing a 'save as' dialog.  

I will have a look though some of the links you have shared as this may be possible to implement using the File System Access API. 

I'll share the other code here shortly.

**Comment by runtimevic** [comment]
> Hi Victor, yes the export plc array / structure to json is possible and I currently do this on another project. The only limitation with the implementation is that it downloads straight to the users download directory, rather than showing a 'save as' dialog.
> 
> I will have a look though some of the links you have shared as this may be possible to implement using the File System Access API.
> 
> I'll share the other code here shortly.

Hi Ben,
thank you very much, if you can pass me the link where you have the export of the array to the Json file?,
 although I do not let you choose locally the path where it is exported ... 
I think with the File System Access API you can do...

**Comment by benhar-dev** [comment]
Hi Victor, I have updated the repo with client side saving.  Next I will look in to how to support server side saving.

**Comment by runtimevic** [comment]
> Hi Victor, I have updated the repo with client side saving. Next I will look in to how to support server side saving.

Hi Ben, 
thank you very much for doing it my level of javascript is beginner...
I close the issue
